#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: ButtonStyleMinusPrimaryMinusMMinusBorderless

#include "Basic.hpp"

#include "CommonUI_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass ButtonStyle-Primary-M-Borderless.ButtonStyle-Primary-M-Borderless_C
// 0x0000 (0x06B0 - 0x06B0)
class UButtonStyleMinusPrimaryMinusMMinusBorderless_C final : public UCommonButtonStyle
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"ButtonStyle-Primary-M-Borderless_C">();
	}
	static class UButtonStyleMinusPrimaryMinusMMinusBorderless_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UButtonStyleMinusPrimaryMinusMMinusBorderless_C>();
	}
};

}

