#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: ButtonStyleMinusBottomBar_BPS18

#include "Basic.hpp"

#include "CommonUI_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass ButtonStyle-BottomBar_BPS18.ButtonStyle-BottomBar_BPS18_C
// 0x0000 (0x06B0 - 0x06B0)
class UButtonStyleMinusBottomBar_BPS18_C final : public UCommonButtonStyle
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"ButtonStyle-BottomBar_BPS18_C">();
	}
	static class UButtonStyleMinusBottomBar_BPS18_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UButtonStyleMinusBottomBar_BPS18_C>();
	}
};

}

