#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: ButtonStyleMinusBacchusBottomBar_Main

#include "Basic.hpp"

#include "CommonUI_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass ButtonStyle-BacchusBottomBar_Main.ButtonStyle-BacchusBottomBar_Main_C
// 0x0000 (0x06B0 - 0x06B0)
class UButtonStyleMinusBacchusBottomBar_Main_C final : public UCommonButtonStyle
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"ButtonStyle-BacchusBottomBar_Main_C">();
	}
	static class UButtonStyleMinusBacchusBottomBar_Main_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UButtonStyleMinusBacchusBottomBar_Main_C>();
	}
};

}

