#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: ButtonStyleMinusClearMinusMin

#include "Basic.hpp"

#include "CommonUI_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass ButtonStyle-Clear-Min.ButtonStyle-Clear-Min_C
// 0x0000 (0x06B0 - 0x06B0)
class UButtonStyleMinusClearMinusMin_C final : public UCommonButtonStyle
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"ButtonStyle-Clear-Min_C">();
	}
	static class UButtonStyleMinusClearMinusMin_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UButtonStyleMinusClearMinusMin_C>();
	}
};

}

