#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: ButtonStyleMinusAngledBlueMinusNoText

#include "Basic.hpp"

#include "CommonUI_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass ButtonStyle-AngledBlue-NoText.ButtonStyle-AngledBlue-NoText_C
// 0x0000 (0x06B0 - 0x06B0)
class UButtonStyleMinusAngledBlueMinusNoText_C final : public UCommonButtonStyle
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"ButtonStyle-AngledBlue-NoText_C">();
	}
	static class UButtonStyleMinusAngledBlueMinusNoText_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UButtonStyleMinusAngledBlueMinusNoText_C>();
	}
};

}

