#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: ButtonStyleMinusEndGameButtonBarMinusBacchus

#include "Basic.hpp"

#include "CommonUI_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass ButtonStyle-EndGameButtonBar-Bacchus.ButtonStyle-EndGameButtonBar-Bacchus_C
// 0x0000 (0x06B0 - 0x06B0)
class UButtonStyleMinusEndGameButtonBarMinusBacchus_C final : public UCommonButtonStyle
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"ButtonStyle-EndGameButtonBar-Bacchus_C">();
	}
	static class UButtonStyleMinusEndGameButtonBarMinusBacchus_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UButtonStyleMinusEndGameButtonBarMinusBacchus_C>();
	}
};

}

