#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: ItemManagementTileButtonStyleMinusAthenaLockerMinusBuiltInEmote

#include "Basic.hpp"

#include "ButtonStyleMinusBase_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass ItemManagementTileButtonStyle-AthenaLocker-BuiltInEmote.ItemManagementTileButtonStyle-AthenaLocker-BuiltInEmote_C
// 0x0000 (0x06B0 - 0x06B0)
class UItemManagementTileButtonStyleMinusAthenaLockerMinusBuiltInEmote_C final : public UButtonStyleMinusBase_C
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"ItemManagementTileButtonStyle-AthenaLocker-BuiltInEmote_C">();
	}
	static class UItemManagementTileButtonStyleMinusAthenaLockerMinusBuiltInEmote_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UItemManagementTileButtonStyleMinusAthenaLockerMinusBuiltInEmote_C>();
	}
};

}

