#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: MovementModeLayerInterface

#include "Basic.hpp"

#include "MovementModeLayerInterface_classes.hpp"
#include "MovementModeLayerInterface_parameters.hpp"


namespace SDK
{

// Function MovementModeLayerInterface.MovementModeLayerInterface_C.MovementMode_LocomotionUpperBodyAdditive
// (HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// struct FPoseLink                        InPose_0                                               (BlueprintVisible, BlueprintReadOnly, Parm, NoDestructor)
// struct FPoseLink                        IdleAdditive_CachedPose                                (BlueprintVisible, BlueprintReadOnly, Parm, NoDestructor)
// struct FPoseLink                        Param_MovementMode_LocomotionUpperBodyAdditive         (Parm, OutParm, NoDestructor)

void IMovementModeLayerInterface_C::MovementMode_LocomotionUpperBodyAdditive(const struct FPoseLink& InPose_0, const struct FPoseLink& IdleAdditive_CachedPose, struct FPoseLink* Param_MovementMode_LocomotionUpperBodyAdditive)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("MovementModeLayerInterface_C", "MovementMode_LocomotionUpperBodyAdditive");

	Params::MovementModeLayerInterface_C_MovementMode_LocomotionUpperBodyAdditive Parms{};

	Parms.InPose_0 = std::move(InPose_0);
	Parms.IdleAdditive_CachedPose = std::move(IdleAdditive_CachedPose);

	UObject::ProcessEvent(Func, &Parms);

	if (Param_MovementMode_LocomotionUpperBodyAdditive != nullptr)
		*Param_MovementMode_LocomotionUpperBodyAdditive = std::move(Parms.Param_MovementMode_LocomotionUpperBodyAdditive);
}


// Function MovementModeLayerInterface.MovementModeLayerInterface_C.MovementMode_LowerBodyOverride
// (HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// struct FPoseLink                        InPose                                                 (BlueprintVisible, BlueprintReadOnly, Parm, NoDestructor)
// struct FPoseLink                        Param_MovementMode_LowerBodyOverride                   (Parm, OutParm, NoDestructor)

void IMovementModeLayerInterface_C::MovementMode_LowerBodyOverride(const struct FPoseLink& InPose, struct FPoseLink* Param_MovementMode_LowerBodyOverride)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("MovementModeLayerInterface_C", "MovementMode_LowerBodyOverride");

	Params::MovementModeLayerInterface_C_MovementMode_LowerBodyOverride Parms{};

	Parms.InPose = std::move(InPose);

	UObject::ProcessEvent(Func, &Parms);

	if (Param_MovementMode_LowerBodyOverride != nullptr)
		*Param_MovementMode_LowerBodyOverride = std::move(Parms.Param_MovementMode_LowerBodyOverride);
}


// Function MovementModeLayerInterface.MovementModeLayerInterface_C.MovementMode_UpperBodyPose
// (HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// struct FPoseLink                        UppperBodyPose_BasePose                                (BlueprintVisible, BlueprintReadOnly, Parm, NoDestructor)
// struct FPoseLink                        UpperBodyPose_AdditiveIdentityPose                     (BlueprintVisible, BlueprintReadOnly, Parm, NoDestructor)
// struct FPoseLink                        Param_MovementMode_UpperBodyPose                       (Parm, OutParm, NoDestructor)

void IMovementModeLayerInterface_C::MovementMode_UpperBodyPose(const struct FPoseLink& UppperBodyPose_BasePose, const struct FPoseLink& UpperBodyPose_AdditiveIdentityPose, struct FPoseLink* Param_MovementMode_UpperBodyPose)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("MovementModeLayerInterface_C", "MovementMode_UpperBodyPose");

	Params::MovementModeLayerInterface_C_MovementMode_UpperBodyPose Parms{};

	Parms.UppperBodyPose_BasePose = std::move(UppperBodyPose_BasePose);
	Parms.UpperBodyPose_AdditiveIdentityPose = std::move(UpperBodyPose_AdditiveIdentityPose);

	UObject::ProcessEvent(Func, &Parms);

	if (Param_MovementMode_UpperBodyPose != nullptr)
		*Param_MovementMode_UpperBodyPose = std::move(Parms.Param_MovementMode_UpperBodyPose);
}

}

