#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: MovementModeLayerInterface

#include "Basic.hpp"

#include "Engine_classes.hpp"


namespace SDK
{

// AnimBlueprintGeneratedClass MovementModeLayerInterface.MovementModeLayerInterface_C
// 0x0000 (0x0028 - 0x0028)
class IMovementModeLayerInterface_C final : public IAnimLayerInterface
{
public:
	void MovementMode_LocomotionUpperBodyAdditive(const struct FPoseLink& InPose_0, const struct FPoseLink& IdleAdditive_CachedPose, struct FPoseLink* Param_MovementMode_LocomotionUpperBodyAdditive);
	void MovementMode_LowerBodyOverride(const struct FPoseLink& InPose, struct FPoseLink* Param_MovementMode_LowerBodyOverride);
	void MovementMode_UpperBodyPose(const struct FPoseLink& UppperBodyPose_BasePose, const struct FPoseLink& UpperBodyPose_AdditiveIdentityPose, struct FPoseLink* Param_MovementMode_UpperBodyPose);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"MovementModeLayerInterface_C">();
	}
	static class IMovementModeLayerInterface_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<IMovementModeLayerInterface_C>();
	}
};

}

