#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: SidebarSettingsRotator_Narrow

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "FortniteUI_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass SidebarSettingsRotator_Narrow.SidebarSettingsRotator_Narrow_C
// 0x0020 (0x0F30 - 0x0F10)
class USidebarSettingsRotator_Narrow_C final : public UFortSettingsRotator
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0F10(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UWidgetAnimation*                       RotatorHover;                                      // 0x0F18(0x0008)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, IsPlainOldData, RepSkip, NoDestructor, HasGetValueTypeHash)
	class UBorder*                                Background;                                        // 0x0F20(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)

public:
	void OnUnHover_Animation();
	void OnHover_Animation();
	void ExecuteUbergraph_SidebarSettingsRotator_Narrow(int32 EntryPoint);
	void BP_OnOptionsPopulated(int32 Count);
	void BP_OnOptionSelected(int32 Param_Index);
	void BP_OnDefaultOptionSpecified(int32 DefaultOptionIndex);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"SidebarSettingsRotator_Narrow_C">();
	}
	static class USidebarSettingsRotator_Narrow_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<USidebarSettingsRotator_Narrow_C>();
	}
};

}

