#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Sidebar_ButtonStyleMinusTabMinusMainMinusRecolorMinusRed

#include "Basic.hpp"

#include "CommonUI_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass Sidebar_ButtonStyle-Tab-Main-Recolor-Red.Sidebar_ButtonStyle-Tab-Main-Recolor-Red_C
// 0x0000 (0x06B0 - 0x06B0)
class USidebar_ButtonStyleMinusTabMinusMainMinusRecolorMinusRed_C final : public UCommonButtonStyle
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"Sidebar_ButtonStyle-Tab-Main-Recolor-Red_C">();
	}
	static class USidebar_ButtonStyleMinusTabMinusMainMinusRecolorMinusRed_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<USidebar_ButtonStyleMinusTabMinusMainMinusRecolorMinusRed_C>();
	}
};

}

