#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Sidebar_TextStyle_BurbSmBk_15_DarkGray

#include "Basic.hpp"

#include "TextStyleMinusBaseParent_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass Sidebar_TextStyle_BurbSmBk_15_DarkGray.Sidebar_TextStyle_BurbSmBk_15_DarkGray_C
// 0x0000 (0x0180 - 0x0180)
class USidebar_TextStyle_BurbSmBk_15_DarkGray_C final : public UTextStyleMinusBaseParent_C
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"Sidebar_TextStyle_BurbSmBk_15_DarkGray_C">();
	}
	static class USidebar_TextStyle_BurbSmBk_15_DarkGray_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<USidebar_TextStyle_BurbSmBk_15_DarkGray_C>();
	}
};

}

