#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: TextStyleMinusSubhead

#include "Basic.hpp"

#include "CommonUI_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass TextStyle-Subhead.TextStyle-Subhead_C
// 0x0000 (0x0180 - 0x0180)
class UTextStyleMinusSubhead_C final : public UCommonTextStyle
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"TextStyle-Subhead_C">();
	}
	static class UTextStyleMinusSubhead_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UTextStyleMinusSubhead_C>();
	}
};

}

