#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: TextStyleMinusHUDMinusBottomBarMinusBBS

#include "Basic.hpp"

#include "TextStyleMinusBaseParent_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass TextStyle-HUD-BottomBar-BBS.TextStyle-HUD-BottomBar-BBS_C
// 0x0000 (0x0180 - 0x0180)
class UTextStyleMinusHUDMinusBottomBarMinusBBS_C final : public UTextStyleMinusBaseParent_C
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"TextStyle-HUD-BottomBar-BBS_C">();
	}
	static class UTextStyleMinusHUDMinusBottomBarMinusBBS_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UTextStyleMinusHUDMinusBottomBarMinusBBS_C>();
	}
};

}

