#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: TextStyleMinusHUDMinusBottomBarMinusBBSMinusDisabled

#include "Basic.hpp"

#include "TextStyleMinusBaseParent_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass TextStyle-HUD-BottomBar-BBS-Disabled.TextStyle-HUD-BottomBar-BBS-Disabled_C
// 0x0000 (0x0180 - 0x0180)
class UTextStyleMinusHUDMinusBottomBarMinusBBSMinusDisabled_C final : public UTextStyleMinusBaseParent_C
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"TextStyle-HUD-BottomBar-BBS-Disabled_C">();
	}
	static class UTextStyleMinusHUDMinusBottomBarMinusBBSMinusDisabled_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UTextStyleMinusHUDMinusBottomBarMinusBBSMinusDisabled_C>();
	}
};

}

