#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: TextStyleMinusHUDMinusBottomBarMinusBBSMinusHovered

#include "Basic.hpp"

#include "TextStyleMinusBaseParent_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass TextStyle-HUD-BottomBar-BBS-Hovered.TextStyle-HUD-BottomBar-BBS-Hovered_C
// 0x0000 (0x0180 - 0x0180)
class UTextStyleMinusHUDMinusBottomBarMinusBBSMinusHovered_C final : public UTextStyleMinusBaseParent_C
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"TextStyle-HUD-BottomBar-BBS-Hovered_C">();
	}
	static class UTextStyleMinusHUDMinusBottomBarMinusBBSMinusHovered_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UTextStyleMinusHUDMinusBottomBarMinusBBSMinusHovered_C>();
	}
};

}

