#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: TextStyleMinusBurbankSmallMinusSMinusS18BP

#include "Basic.hpp"

#include "TextStyleMinusBaseParent_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass TextStyle-BurbankSmall-S-S18BP.TextStyle-BurbankSmall-S-S18BP_C
// 0x0000 (0x0180 - 0x0180)
class UTextStyleMinusBurbankSmallMinusSMinusS18BP_C final : public UTextStyleMinusBaseParent_C
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"TextStyle-BurbankSmall-S-S18BP_C">();
	}
	static class UTextStyleMinusBurbankSmallMinusSMinusS18BP_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UTextStyleMinusBurbankSmallMinusSMinusS18BP_C>();
	}
};

}

