#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: VaultWorld

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "FortniteUI_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass VaultWorld.VaultWorld_C
// 0x0010 (0x02D8 - 0x02C8)
class AVaultWorld_C : public AFortItemPreviewWorld
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x02C8(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	bool                                          bIsPrimaryBackgroundActive;                        // 0x02D0(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	void OnUpdateDisplay(bool bShowFloor, bool bShowEffects);
	void OnTransitionItemDetails(const bool bShowItemDetails);
	void ReceiveBeginPlay();
	void OnTransitionBackground(bool bPlayForward);
	void OnSetupBackground(const class UTexture2D* LoadedBackgroundTexture, const struct FTrackDynamicBackground& BackgroundInfo);
	void ExecuteUbergraph_VaultWorld(int32 EntryPoint);
	void GetVaultRotator(class AVaultRotator_C** VaultRotator);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"VaultWorld_C">();
	}
	static class AVaultWorld_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AVaultWorld_C>();
	}
};

}

